language: cpp
python: '3.6'
dist: trusty
env:
  global:
  - secure: RNbJ4k1F1YVL9sgG5w77eK55S+pLIV9TTKGPTmcR+BKjFM5DX7FgLH9xsV60n3rXfwoMUizFO5/AoFrHr7h/F+HpPa5rR+3b61LAHTJ9wCB/nbmbmgqIhlzVcAjWy0kwiLZh1zCS4g/yr3q8uCbgRWhQBCGEciAeuS4PYjK8T8GazOS1ic4CeDDRbOUPFkjoLQzGj5tM7DkaAqORFau0gtKfnpK4Qfc4HMZy28kSq0d8BQSl9V6t0Yj6jtHcIxO9TJqdvHOKALDqWltisnzShHcOPvgn2aV1b3qKz/dl5tQaWDGQPcdkXiK5e67DOVoswEJ5fDKGC+ptIUJYU+e+7cnx51O2qdDAwGxCsozN+8DY/LMVspraMvDvC9kBTNM6hHXRcbv8GiISKigq+yjfSQ7WqNoWYEO18mgN/UcJT3HUI4j2EDj8ZTt73/6s6f/DrT4SU7grQVp0MNR6GD8e8prpY49vjZRaz1sTH/xIdKHNpVLnuUHz8+SEevFxCkA9+dywFu6TbamNZpRfg650VhQjiSSOKOwN5GmR1m92SQ8abkzFfedtlufdcwNOPdmA0/xmXizmZTbXXyRkDKfIccKVxiI2miSO4JTS0nUzufdHvH0Sx2/Jz3DBJVbWZU2Wpoq74AX+x0mJiWsldnbvKeNOJArsHB45+PbmgMNP/2k=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
    - g++-7
    - clang-7
    - clang-tidy-7
    - clang-format-7
  coverity_scan:
    project:
      name: lemourin/libcloudstorage
      description: Build submitted via Travis CI
    notification_email: pawel.wegner95@gmail.com
    build_command_prepend: cov-configure --comptype gcc --compiler gcc-7 --template && mkdir build-coverity && cd build-coverity && CXX=g++-7 CC=gcc-7 cmake .. -DCMAKE_PREFIX_PATH=$PWD/../contrib/x86_64-linux-gnu
    build_command: make -j 4
    branch_pattern: coverity

before_install:
- for i in $(find test src bin examples -type f \( -regex '.*\.\(h\|cpp\|c\)$' ! -regex 'test/googletest/.*$' \)); do
    clang-format-7 $i | diff - $i > /dev/null;
    if [[ $? -ne 0 ]]; then
      echo "File $i not formatted.";
      FAIL=true;
    fi;
  done;
  [ "$FAIL" != "true" ]
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- cd contrib
- wget -nc https://github.com/lemourin/libcloudstorage/releases/download/1.5-rc1/x86_64-linux-gnu.tar.gz
- tar xf x86_64-linux-gnu.tar.gz
- ./change-prefix.sh
- wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh
- chmod +x cmake-3.17.3-Linux-x86_64.sh
- ./cmake-3.17.3-Linux-x86_64.sh --skip-license --prefix=$PWD/x86_64-linux-gnu
- export PATH="$PWD/x86_64-linux-gnu/bin:$PATH"
- cd ..

script:
- mkdir build
- cd build
- export PKG_CONFIG_PATH=$PWD/../contrib/x86_64-linux-gnu/lib/pkgconfig
- CXXFLAGS="-Wall -Wextra -Werror -g -O0 -fsanitize=address"
  LDFLAGS="-static-libasan -fsanitize=address" CC=gcc-7 CXX=g++-7 cmake .. -DCMAKE_PREFIX_PATH=$PWD/../contrib/x86_64-linux-gnu
- LD_LIBRARY_PATH=$PWD/../contrib/x86_64-linux-gnu/lib make -j 4
- LD_LIBRARY_PATH=$PWD/../contrib/x86_64-linux-gnu/lib make test CXXFLAGS=-Wno-sign-compare -j 4
- cd ..
- clang-tidy-7 $(find src bin test examples -name "*.cpp") --
  -Isrc -Ibin/cloudbrowser/src -Itest $(pkg-config --cflags jsoncpp Qt5Quick fuse3)
  -Itest/googletest/googletest/include
  -Itest/googletest/googlemock/include
  -Ibuild/src
  -DWITH_FUSE -DWITH_MPV -DWITH_CURL -DWITH_MICROHTTPD -DWITH_THUMBNAILER -DWITH_CRYPTOPP -fPIC

before_deploy:
- CC=gcc-7 CXX=g++-7 ./packaging/appimage/create-appimage.sh

deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: FKvjbAn/91TRlQMOYO3Bsfx3IYe+BEAkjS/EGfEiR7WKh0Xz2c6HzDucKuNq0MuPPh8ddQO+szVWwSJXMG2brXQtKuRPdPARGLOiR3R8+F2UAnQ6o3AVoXcpZCVYgqZzg4gz8I7+LhL+48UKhNykU4DT3ahtL9kAmMmBbI4sl84WEwSxw7QHMKD8y/fVskyBYOzg1uT1sbmiupy0oErJyi+s8faYLcVPmremWZeJL5pra76+xjO9siriIscOKPONknKu7w2s7AeVHdW4VEmkc4iLVUpz0xsUWaoIaX16smkVtz3pE34UBigO1JyJPqYO+c2CNDqXOJwN+xx1GIqL65vColrZB9IkRdfa0chmIy6c05ZvDpyZtNwOBqImBx6kod34URpz+kwwKK+9a56HcDrXYUZ+Knmcm/4t6LSH51QksjLLxqnI2wqDvmohUkyo3cZfPw8bBB0c7NRwVDNStQLxKnsXfZ8H58uYd3XhERGn2/D13JX0VvRb8lUMwSWsLADng1oLfe8ITiD46NzdUwOCgcS3NYlM51l8q6D00QMlzCqDGJeFI/lFR2a4o5xhXYkx3Dn5cAj6D1i+O0WLSDLOP7ILIuNKP5E5msTvvpuslaUMM/oEwLl0WnVkRpSKSxLBAi5bQL3xQo64PO9oCvnC/37sa/0NCdfiI99nXfE=
  file: "packaging/appimage/build/Cloud_Browser-x86_64.AppImage"
  skip_cleanup: true
  on:
    tags: true
